CREATE DATABASE IF NOT EXISTS pet_store;
USE pet_store;

CREATE TABLE IF NOT EXISTS pets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    species VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    image_url VARCHAR(512) NULL
);
